from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package='sensor_pkg',
            executable='imu_node',
            name='imu_node',
            output='screen'
        ),
        Node(
            package='sensor_pkg',
            executable='odom_publisher',
            name='odom_publisher',
            output='screen'
        ),
        Node(
            package='sensor_pkg',
            executable='md_control',
            name='md_control',
            output='screen'
        ),
        Node(
            package='sensor_pkg',
            executable='uwb_to_ros',
            name='uwb_to_ros',
            output='screen'
        ),
        Node(
            package='sensor_pkg',
            executable='uwb_offset_node',
            name='uwb_offset_node',
            output='screen'
        ),
        Node(
            package='sensor_pkg',
            executable='uwb_tf_broadcaster',
            name='uwb_tf_broadcaster',
            output='screen'
        ),
        Node(
            package='sensor_pkg',
            executable='ultrasonic_parser_node',
            name='ultrasonic_parser_node',
            output='screen'
        ),
        Node(
            package='sensor_pkg',
            executable='obstacle_detector_node',
            name='obstacle_detector_node',
            output='screen'
        ),
        Node(
            package='sensor_pkg',
            executable='battery_reader_node',
            name='battery_reader_node',
            output='screen'
        ),
    ])
